### ISSUE TITLE
Creation of new user profile: bug and not user friendly

### ISSUE THREAD

**Issue by gmassard** [Leadera/ecoman_repo#305] opened 2015-05-20 07:20 UTC
When a new user register, there are some bugs.
When you click on "create user profile", the tool display a "Request ....". And then? The user does not know what to do...
When the new user click on "create user profile", can the tool directly display  its user profile page? And also, can he be logged in automaticaly. 

Now, he has to understand alone, that he is not "Signed In" and if he goes to the "member" / "consultant" page, and then click on his name, the following screen... Not very sexy!

![geneva_test_4](https://cloud.githubusercontent.com/assets/9587966/7720767/6a1b10ea-fed1-11e4-8f75-6947bfe33036.png)

**Comment by tcgumus** [comment] 2015-09-10 09:19
It was caused by the usernames includes spaces in it. Now we are making this control. You won't see this error again. If it occurs please open this issue. I'm closing it right now since it should be solved.

**Closed by tcgumus** 2015-09-10 09:19 UTC
Labels: bug, Portal, urgent
