### ISSUE TITLE
Create project page: contact person sometime can't not be choosen

### ISSUE THREAD

**Issue by gmassard** [Leadera/ecoman_repo#143] opened 2015-02-17 09:22 UTC
On the create project page, I can't select a contact person when this contact is not existing for a company. When I click on create project, I get an error page.
The project is being created on the database, but an error page is displayed.

**Comment by tcgumus** [comment] 2015-02-17 10:36
Hello. Can you share the error you get?

**Comment by corner82** [comment] 2015-02-17 10:40
![bug](https://cloud.githubusercontent.com/assets/5053878/6226854/12ff9d2a-b6a2-11e4-8a5f-3aeac1df1876.png)

Here is the error page....

**Comment by tcgumus** [comment] 2015-02-17 10:43
Contact person selection only shows the users who are also confact person or creator of a company. We thought you shouldnt be able to add a contact person who is not working on a project. We can change this filter if you want but please define which user can we add.

**Comment by tcgumus** [comment] 2015-02-17 10:45
Thank you. I will look and respond asap.

**Comment by corner82** [comment] 2015-02-17 10:50
When creating a new project , I choose company 'Ada Kaucuk', choose consultant as myself, but contact person dropdown still does not fill, so I can't choose a contact person, probably beacuse of that this error page shows up, I send screen shot to show form data inputs ...

![bug2](https://cloud.githubusercontent.com/assets/5053878/6227026/7634381e-b6a3-11e4-9de0-5218399b1153.png)

**Comment by tcgumus** [comment] 2015-02-17 11:05
Thank you. I will look it after meal :)

**Comment by tcgumus** [comment] 2015-02-17 11:56
Hello,
Problem was caused by empty contact person field. I have added a control for that. So you now cant able to create a project without selecting a contact person. So you wont see the error page again.

The problem causing not to show a contact person when you select a company is that we were created some of the companies through from database directly to test the IS scoping pages before releasing it. 

So some of the company didn't have a contact person until now that causes empty contact person field.  But now i have added Mr. Zeynel to all empty companies as a contact person from "t_cmpny_prsnl". I have tested the issue and it looks like problem solved and from then on we shouldn't see any empty contact person field but if you see it please contact me :+1: 

Please test and respond. Thank you.

**Comment by MildaMa** [comment] 2015-02-18 09:35
Hi, 
it doesn`t work properly for me:
1. I can assign the contact person in the beginning , but it doesn`t create new Project. I get the error (see attached screenshot),
2. After getting the error I go back to the "create project" page. I can`t assign the contact Person anymore, which also means I can`t create new Project. 
![create project error 1 2015 02 18](https://cloud.githubusercontent.com/assets/9460158/6244932/a21f1118-b759-11e4-810f-9924e037e098.png)

**Comment by tcgumus** [comment] 2015-02-18 11:17
Hello Milda,
The error says you entered the wrong integer value since you didnt enter any "zoom level" value. So thats why it gives an error. I created a new control for this field. So from then on you cant leave empty "zoom level" field. Can you please try again?
Thank you

**Comment by corner82** [comment] 2015-02-18 11:24
Hello everyone, 
'zoom level' parameter does not have to be required, from Html form side 'zoom level' parameter is being controlled for being integer or two digits vs, but while inserting into database if 'zoom level' data is null 'insert' statement should be fixed I think, so the end user does not need to set unnecessary field if user does not want to fill 'zoom level' input.

**Comment by tcgumus** [comment] 2015-02-18 11:39
Hello :)
I change the requirement of the zoom level field and make an empty control in business logic. I have tested it in live in a project. You should be able to create a project without entering a zoom level now.

**Comment by MildaMa** [comment] 2015-02-18 13:35
yes, seems that it works now. thanks!!!

**Closed** 2015-04-24 10:21 UTC
Labels: bug, General Pages, urgent, waiting for testing
