### ISSUE TITLE
Automated IS: STEP 1 flow tree

### ISSUE THREAD

**Issue by gmassard** [Leadera/ecoman_repo#312] opened 2015-05-21 08:23 UTC
When clicking on category dot, do not open the tree.

**Comment by corner82** [comment] 2015-08-03 20:49
When clicking on category dot,the tree will not be opened.

**Comment by gmassard** [comment] 2015-08-10 07:29
I have to reopen this issue. When you click on category dot, the dot is clicked and the flow three does not open. But the category is not taking into account during the IS detection.
A category is still only taken into account in the detection when you click the little arrow that open the flow three...
This bug need to be fixed.

**Comment by gmassard** [comment] 2015-08-10 07:29
Please ask for testing when the changes are done.

**Comment by corner82** [comment] 2015-08-16 16:57
sorry this is not a bug , this is the way 'easyui javascript library' works... there is  'onexpand' , 'oncheck', 'oncollapse' , 'ondoublecheck' events the user must set one of these events to get the child nodes on tree, if you dont fire one of these events and expand related node you can not upload child nodes from server and you cannot use child nodes (flows) in the IS detection, so this is not a bug (but you may consider it as a bug of course).
I have told this issue with Guillaume in detail before and I stated then 'I will look for shortcuts if I may', now I examined related events and tried to fire them in a chain but the results are not good.
So this tree structure works as it is, it is working till the day it was implemented, only the user will check arrow or the checkbox, that is it, closing issue, from development approach, this issue closed....

**Closed by corner82** 2015-08-16 16:57 UTC
Labels: bug, IS Scoping, refinement, urgent

**Comment by corner82** [comment] 2015-08-18 12:16
Dropbox IS-GIS document IS-05 scenario
