### ISSUE TITLE
Open project and close project features will be added.

### ISSUE THREAD

**Issue by tcgumus** [Leadera/ecoman_repo#134] opened 2015-02-04 13:35 UTC
- Open project functions coded.
- Close project functions coded.
- Link controls for header added.
- Open project page only shows projects that user can edit.
- CBA graph table added but doesnt work now.
- Routes added.

**Comment by gmassard** [comment] 2015-02-06 16:18
http://88.249.18.205:8090/ecoman/projects
The project page showing only the project related to one user is good. But I do not understand the "Open a project" link. How is it working?
The "Show all project" page is enough. When a click on a project link, the project should be open automatically. Then once inside a specific, I can not find anymore the links to CP scoping and IS scoping. Where are they?
The navigability is not good and the issue is not solve. I'm reopening this issue.

**Comment by gmassard** [comment] 2015-02-06 16:34
In addition, the are no navigability.
"Edit project", " project", a search field for project. Basics info display on the projet: country, date of creation, alphabetical order...
In my opinion, this are basic programmer work.

**Comment by tcgumus** [comment] 2015-02-06 16:37
Showing project details and opening a project are different things. You should click on the "open project button" and select a project to work on.  Then you can see the links you needed. With this way we can enable free roaming through website and working on a selected project at the same time.

If we change it as you like, users cant see the other projects details when they selected a project.

**Comment by gmassard** [comment] 2015-02-06 16:40
This two features you mention should be merged. Also, when I click on "Open a project", I get a 404 page not found message. http://88.249.18.205:8090/ecoman/openproject

I do not know what it means to enable free roaming throughout the web site or not. What I see as user does not work so far and do not appear user friendly at all.

**Comment by tcgumus** [comment] 2015-02-06 16:42
Search field are also working for projects. 
Edit project button are in the project pages. You should define where are you want this information. All information you mentioned are already displayed in the project pages.

**Comment by tcgumus** [comment] 2015-02-06 16:47
Please mention the 404 pages first :) I will look for it and write a reply. I think thats why you didnt understand the open project button.

**Comment by tcgumus** [comment] 2015-02-09 15:17
You can now "open a project" and work on it in IS scoping but implementation for CP Scoping, KPI calculation other general views will be handled this week. I will let you know when i make bulk changes.

**Comment by tcgumus** [comment] 2015-02-12 07:43
Project management issue looks like resolved. Please test and respond.

**Comment by gmassard** [comment] 2015-02-13 09:44
Hi!
The open and close project seems to work. Thank you for your work!
By testing the functionally, I have few more comment to make for improvement:
1. After entering a project, when I click on the "company" link, I can still see all the companies in the database. It is good that a can modify info from the companies in the project I'm logged in. But I should not be able to see all companies in the database. Can we change that? Maybe the company button should be remove from the main page and link to company and edition improve on the project page (http://88.249.18.205:8090/ecoman/project/19).
2. Once inside a project, when I click on update project info, I can still see every company in the database and add them to my project. How do I avoid seeing all companies, and only see or select companies that are related to me (either I create the company, or the company register and contacted me to enter a project). The problem now is that I can add every company to me project. One added, I can see and change the data of this company. So, confidentiality of not respected.

Zeynel and I discuss it in Hangout meeting. So Tuna, please communicate with Zeynel for details.

**Comment by tcgumus** [comment] 2015-02-18 08:02
Requirement unclear. We think it needs to be discussed in a meeting.

**Comment by gmassard** [comment] 2015-02-27 10:16
Hi Tuna,

You mentioned requirement unclear. Did you discuss with Zeynel as I asked for?

I have done a new test from scratch. The project feature works (except for the company page, see issue number 97 that need to be solve).

From my perspective, only the navigability and page organization, links between page need to be improve for the first version.

**Comment by tcgumus** [comment] 2015-05-15 08:31
Maybe we should talk about it in geneva. Some of the problems mentioned here are solved by portal implementation.

**Closed** 2015-09-10 08:59 UTC
Labels: enhancement, General Pages, urgent, waiting for testing
